# Generated by Django 4.1.7 on 2023-05-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0013_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance801",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("student_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "attendance_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("class_time", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "attendance_801",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
    ]
