# Generated by Django 4.1.7 on 2023-05-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0012_accattendance_class_proinfo_stuinfo_usergroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
    ]
