# Generated by Django 4.1.7 on 2023-05-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0016_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccAttendanceElite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_id", models.CharField(blank=True, max_length=50, null=True)),
                ("stu_name", models.CharField(blank=True, max_length=50, null=True)),
                ("att_score", models.IntegerField(blank=True, null=True)),
                ("acc_att_score", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "acc_attendance_elite",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Attendance80131337",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "attendance_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("class_time", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "attendance_801_31337",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Attendance801Elite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("class_time", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "attendance_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("late_count", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "attendance_801_elite",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserElite",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(blank=True, max_length=125, null=True)),
                (
                    "username",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "usermajor",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
            ],
            options={
                "db_table": "user_elite",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserGroupElite",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("group", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "user_group_elite",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="AccAttendance",
        ),
        migrations.DeleteModel(
            name="Attendance801",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="ProInfo",
        ),
        migrations.DeleteModel(
            name="StuInfo",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.DeleteModel(
            name="UserGroup",
        ),
        migrations.CreateModel(
            name="ProInfoElite",
            fields=[
                (
                    "pro",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="pro_info",
                        serialize=False,
                        to="check.userelite",
                    ),
                ),
            ],
            options={
                "db_table": "pro_info_elite",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StuInfoElite",
            fields=[
                (
                    "stu",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="stu_info",
                        serialize=False,
                        to="check.userelite",
                    ),
                ),
            ],
            options={
                "db_table": "stu_info_elite",
                "managed": False,
            },
        ),
    ]
