# Generated by Django 4.1.7 on 2023-05-28 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0017_accattendanceelite_attendance80131337_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User31337",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(blank=True, max_length=125, null=True)),
                (
                    "username",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("usermajor", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "user_31337",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserGroup31337",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("group", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "user_group_31337",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProInfo31337",
            fields=[
                (
                    "pro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="proinfo31337_pro",
                        serialize=False,
                        to="check.user31337",
                    ),
                ),
                ("pro_name", models.CharField(blank=True, max_length=50, null=True)),
                ("pro_major", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "pro_info_31337",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StuInfo31337",
            fields=[
                (
                    "stu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="stuinfo31337_stu",
                        serialize=False,
                        to="check.user31337",
                    ),
                ),
                ("stu_name", models.CharField(blank=True, max_length=50, null=True)),
                ("stu_major", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "stu_info_31337",
                "managed": False,
            },
        ),
    ]
