# Generated by Django 4.1.7 on 2023-06-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0018_user31337_usergroup31337_proinfo31337_stuinfo31337"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(blank=True, max_length=125, null=True)),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                ("usermajor", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("group", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "user_group",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="AccAttendanceElite",
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.DeleteModel(
            name="AuthGroup",
        ),
        migrations.DeleteModel(
            name="AuthGroupPermissions",
        ),
        migrations.DeleteModel(
            name="AuthPermission",
        ),
        migrations.DeleteModel(
            name="AuthUser",
        ),
        migrations.DeleteModel(
            name="AuthUserGroups",
        ),
        migrations.DeleteModel(
            name="AuthUserUserPermissions",
        ),
        migrations.DeleteModel(
            name="DjangoAdminLog",
        ),
        migrations.DeleteModel(
            name="DjangoContentType",
        ),
        migrations.DeleteModel(
            name="DjangoMigrations",
        ),
        migrations.DeleteModel(
            name="DjangoSession",
        ),
        migrations.DeleteModel(
            name="Images",
        ),
        migrations.RemoveField(
            model_name="proinfo31337",
            name="pro",
        ),
        migrations.RemoveField(
            model_name="proinfoelite",
            name="pro",
        ),
        migrations.RemoveField(
            model_name="stuinfo31337",
            name="stu",
        ),
        migrations.RemoveField(
            model_name="stuinfoelite",
            name="stu",
        ),
        migrations.DeleteModel(
            name="UserGroup31337",
        ),
        migrations.DeleteModel(
            name="UserGroupElite",
        ),
        migrations.CreateModel(
            name="AccAtt801",
            fields=[
                (
                    "stu",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="check.user",
                    ),
                ),
                (
                    "number_1week",
                    models.CharField(
                        blank=True, db_column="1week", max_length=50, null=True
                    ),
                ),
                (
                    "number_2week",
                    models.CharField(
                        blank=True, db_column="2week", max_length=50, null=True
                    ),
                ),
                (
                    "number_3week",
                    models.CharField(
                        blank=True, db_column="3week", max_length=50, null=True
                    ),
                ),
                (
                    "number_4week",
                    models.CharField(
                        blank=True, db_column="4week", max_length=50, null=True
                    ),
                ),
                (
                    "number_5week",
                    models.CharField(
                        blank=True, db_column="5week", max_length=50, null=True
                    ),
                ),
                (
                    "number_6week",
                    models.CharField(
                        blank=True, db_column="6week", max_length=50, null=True
                    ),
                ),
                (
                    "number_7week",
                    models.CharField(
                        blank=True, db_column="7week", max_length=50, null=True
                    ),
                ),
                (
                    "number_8week",
                    models.CharField(
                        blank=True, db_column="8week", max_length=50, null=True
                    ),
                ),
                (
                    "number_9week",
                    models.CharField(
                        blank=True, db_column="9week", max_length=50, null=True
                    ),
                ),
                (
                    "number_10week",
                    models.CharField(
                        blank=True, db_column="10week", max_length=50, null=True
                    ),
                ),
                (
                    "number_11week",
                    models.CharField(
                        blank=True, db_column="11week", max_length=50, null=True
                    ),
                ),
                (
                    "number_12week",
                    models.CharField(
                        blank=True, db_column="12week", max_length=50, null=True
                    ),
                ),
                (
                    "number_13week",
                    models.CharField(
                        blank=True, db_column="13week", max_length=50, null=True
                    ),
                ),
                (
                    "number_14week",
                    models.CharField(
                        blank=True, db_column="14week", max_length=50, null=True
                    ),
                ),
                (
                    "number_15week",
                    models.CharField(
                        blank=True, db_column="15week", max_length=50, null=True
                    ),
                ),
                ("acc_att_score", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "acc_att_801",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="ProInfo31337",
        ),
        migrations.DeleteModel(
            name="ProInfoElite",
        ),
        migrations.DeleteModel(
            name="StuInfo31337",
        ),
        migrations.DeleteModel(
            name="StuInfoElite",
        ),
        migrations.DeleteModel(
            name="User31337",
        ),
        migrations.DeleteModel(
            name="UserElite",
        ),
    ]
