# Generated by Django 4.1.7 on 2023-05-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0007_authgroup_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "attendance_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("class_time", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "_801_attendance",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="CheckCustomuser",
        ),
        migrations.DeleteModel(
            name="CheckCustomuserGroups",
        ),
        migrations.DeleteModel(
            name="CheckCustomuserUserPermissions",
        ),
        migrations.DeleteModel(
            name="eAttendance",
        ),
    ]
