# Generated by Django 4.1.7 on 2023-05-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0011_authgroup_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_id", models.CharField(blank=True, max_length=50, null=True)),
                ("att_status", models.CharField(blank=True, max_length=50, null=True)),
                ("att_score", models.IntegerField(blank=True, null=True)),
                ("acc_att_score", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "acc_attendance",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("subject", models.CharField(blank=True, max_length=50, null=True)),
                ("time_start", models.TimeField(blank=True, null=True)),
                ("time_end", models.TimeField(blank=True, null=True)),
                ("day_of_week", models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                "db_table": "class",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProInfo",
            fields=[
                (
                    "pro_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "pro_password",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pro_major", models.CharField(blank=True, max_length=50, null=True)),
                ("pro_name", models.CharField(blank=True, max_length=50, null=True)),
                ("pro_group", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "pro_info",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StuInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "stu_password",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("stu_major", models.CharField(blank=True, max_length=50, null=True)),
                ("stu_name", models.CharField(blank=True, max_length=50, null=True)),
                ("stu_group", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "stu_info",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "user_group",
                "managed": False,
            },
        ),
    ]
