# Generated by Django 4.1.7 on 2023-05-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0014_attendance801_delete_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_id", models.CharField(blank=True, max_length=50, null=True)),
                ("stu_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "attendance_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("attendance_score", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "attendance",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="AuthGroupPermissions",
        ),
        migrations.DeleteModel(
            name="AuthPermission",
        ),
        migrations.DeleteModel(
            name="AuthUserUserPermissions",
        ),
        migrations.DeleteModel(
            name="DjangoSession",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
